/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  IEventBus,
  IUser,
} from 'core';


export namespace Components {
  interface UserInfo {
    'appEvents': IEventBus;
  }
  interface UserLoginPopup {
    'visible': boolean;
  }
}

declare global {


  interface HTMLUserInfoElement extends Components.UserInfo, HTMLStencilElement {}
  var HTMLUserInfoElement: {
    prototype: HTMLUserInfoElement;
    new (): HTMLUserInfoElement;
  };

  interface HTMLUserLoginPopupElement extends Components.UserLoginPopup, HTMLStencilElement {}
  var HTMLUserLoginPopupElement: {
    prototype: HTMLUserLoginPopupElement;
    new (): HTMLUserLoginPopupElement;
  };
  interface HTMLElementTagNameMap {
    'user-info': HTMLUserInfoElement;
    'user-login-popup': HTMLUserLoginPopupElement;
  }
}

declare namespace LocalJSX {
  interface UserInfo extends JSXBase.HTMLAttributes<HTMLUserInfoElement> {
    'appEvents'?: IEventBus;
  }
  interface UserLoginPopup extends JSXBase.HTMLAttributes<HTMLUserLoginPopupElement> {
    'onClosed'?: (event: CustomEvent<void>) => void;
    'onLoggedIn'?: (event: CustomEvent<IUser>) => void;
    'visible'?: boolean;
  }

  interface IntrinsicElements {
    'user-info': UserInfo;
    'user-login-popup': UserLoginPopup;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


