/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  IEventBus,
} from 'core';


export namespace Components {
  interface HeaderThemeSwitcher {}
  interface HeaderTopBar {
    'appEvents': IEventBus;
  }
}

declare namespace LocalJSX {
  interface HeaderThemeSwitcher extends JSXBase.HTMLAttributes {
    'onThemeSelected'?: (event: CustomEvent<string>) => void;
  }
  interface HeaderTopBar extends JSXBase.HTMLAttributes {
    'appEvents'?: IEventBus;
  }

  interface IntrinsicElements {
    'header-theme-switcher': HeaderThemeSwitcher;
    'header-top-bar': HeaderTopBar;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


declare global {



  interface HTMLHeaderThemeSwitcherElement extends Components.HeaderThemeSwitcher, HTMLStencilElement {}
  var HTMLHeaderThemeSwitcherElement: {
    prototype: HTMLHeaderThemeSwitcherElement;
    new (): HTMLHeaderThemeSwitcherElement;
  };

  interface HTMLHeaderTopBarElement extends Components.HeaderTopBar, HTMLStencilElement {}
  var HTMLHeaderTopBarElement: {
    prototype: HTMLHeaderTopBarElement;
    new (): HTMLHeaderTopBarElement;
  };

  interface HTMLElementTagNameMap {
    'header-theme-switcher': HTMLHeaderThemeSwitcherElement;
    'header-top-bar': HTMLHeaderTopBarElement;
  }

  interface ElementTagNameMap extends HTMLElementTagNameMap {}
}

