/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  IEventBus,
  IItem,
} from 'core';


export namespace Components {
  interface SearchBar {
    'appEvents': IEventBus;
  }
  interface SearchItem {
    'record': IItem;
  }
  interface SearchResults {
    'appEvents': IEventBus;
  }
}

declare namespace LocalJSX {
  interface SearchBar extends JSXBase.HTMLAttributes {
    'appEvents'?: IEventBus;
  }
  interface SearchItem extends JSXBase.HTMLAttributes {
    'onRemoved'?: (event: CustomEvent<IItem>) => void;
    'onSaved'?: (event: CustomEvent<IItem>) => void;
    'record': IItem;
  }
  interface SearchResults extends JSXBase.HTMLAttributes {
    'appEvents'?: IEventBus;
  }

  interface IntrinsicElements {
    'search-bar': SearchBar;
    'search-item': SearchItem;
    'search-results': SearchResults;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


declare global {



  interface HTMLSearchBarElement extends Components.SearchBar, HTMLStencilElement {}
  var HTMLSearchBarElement: {
    prototype: HTMLSearchBarElement;
    new (): HTMLSearchBarElement;
  };

  interface HTMLSearchItemElement extends Components.SearchItem, HTMLStencilElement {}
  var HTMLSearchItemElement: {
    prototype: HTMLSearchItemElement;
    new (): HTMLSearchItemElement;
  };

  interface HTMLSearchResultsElement extends Components.SearchResults, HTMLStencilElement {}
  var HTMLSearchResultsElement: {
    prototype: HTMLSearchResultsElement;
    new (): HTMLSearchResultsElement;
  };

  interface HTMLElementTagNameMap {
    'search-bar': HTMLSearchBarElement;
    'search-item': HTMLSearchItemElement;
    'search-results': HTMLSearchResultsElement;
  }

  interface ElementTagNameMap extends HTMLElementTagNameMap {}
}

